### PR TITLE
Issue #222: Fixed wrong chart data subscription after reloading

### LINKED ISSUE #222: [BUG] Загрузка страницы и хранилище переменных
### Опишите баг

При первоначальной загрузке страницы грузится SBER:MOEX.
Если в инструментах выбрать зарубежную бумагу, а потом обновить страницу, то виджеты снова переключаются на SBER, но график пытается рисоваться по прошлой бумаге. После этого терминал становится неработоспособным.

https://user-images.githubusercontent.com/99450543/172658569-fb0a882a-4ce1-418b-ab40-e729717f7fab.mp4

### Воспроизведение

1. Открыть начальную страницу. Загружена биржа MOEX, инструмент SBER
2. В инструментах открыть зарубежную бумагу. Все виджеты переключились на нее.
3. Обновить терминал по F5.

### Среда.

Windows 10, Chrome Canary 104.0.5108.0

### Ожидаемое поведение

При обновлении страницы не использовать данные от прошлого инструмента.
либо
При обновлении страницы брать последнюю бумагу и открывать ее (описал в #221)

### Скриншоты

_No response_

### Дополнительная информация

_No response_

### Правила

- [ ] Я согласен следовать правилам

### PR DESCRIPTION
**Pull request by sbelashevskiy**
Fixes #222 

# Description

Fixed wrong chart data subscription after reloading

# Testing

Execute steps from issue description

# Risk

No major changes

# Do you agree with those?
- [x] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [x] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/app/shared/utils/observable-helper.ts [hunk 1]
```diff
@@ -18,3 +26,13 @@ export function catchHttpError<T>(valueToReturn: T, errorHandler?: ErrorHandlerS
     })
   );
 }
+
+export function mapWith<T1, T2, R>(project: (value: T1) => Observable<T2>, resultSelector: (a: T1, b: T2) => R): OperatorFunction<T1, R> {
```
Comment (PilgrimViis) [inline src/app/shared/utils/observable-helper.ts:30]: Добавь пожалуйста комментарий с описанием метода, параметров и результата.
