### PR TITLE
#1658 fix price step in price fields

### LINKED ISSUE #1658: [BUG] Цена не меняется по шагу цены по бумаге в Корзине заявок и Заявка
### Опишите баг

Сейчас в виджете "Корзина заявок" для поля "цена" при нажатии "вверх-вниз" на клавиатуре или при прокручивании колесиком мыши для всех бумаг - шаг цены всегда равен 0.1, из-за этого возникают ошибки валидации для бумаг с minstep=1 (LENT) или же сбрасывается мелкий шаг цены (VTBR) - видно на видео:

https://github.com/alor-broker/Astras-Trading-UI/assets/88287882/695bdbf2-f762-48f4-aea6-c73377c0e87a

И также для виджета и модалки "Заявка" (таб Лимитная) для блока "Условная заявка сверху (≥)" или "Условная заявка снизу"  - тут значение всегда ±1 (на клавиатуре или колесиком мыши). Хотя в табе "Условная" поле с triggerPrice меняется на шаг цены по инструменту:
2024-05-03_14h36_36

### Воспроизведение

1. Выставить виджет "Корзина заявок". 
2. Выбрать LENT и VTBR.
3. Для Ленты прокрутить колесо мыши вверх в поле "Цена".
4. Для VTBR нажать "вниз" на клавиатуре.
5. Проверить смену цены для бумаг.
6. В модалке "Заявка" в блоке "Продвинутые" для полей "Условная заявка сверху" и "Условная заявка снизу" проверить смену цены через стрелки "вверх-вниз" на клавиатуре или при прокручивании колесиком мыши.

### Среда.

Windows 10
Google Chrome v120

### Ожидаемое поведение

1. В Корзине заявок и в виджете и модалке "Заявка" при нажатии "вверх-вниз" на клавиатуре или при прокручивании колесиком мыши в поле "Цена" и "Условная заявка.." цена меняется по шагу цену по указанному инструменту.

### Скриншоты

_No response_

### Дополнительная информация

_No response_

### Правила

- [X] Я согласен следовать правилам

### PR DESCRIPTION
**Pull request by agushasok**
Fixes #1658 

# Description

fix price step in price fields

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.ts [hunk 1]
```diff
@@ -247,6 +247,14 @@ export class OrdersBasketItemComponent implements OnInit, OnDestroy, ControlValu
     });
 
     this.form.controls.price.addAsyncValidators(AtsValidators.priceStepMultiplicityAsync(this.instrument$.pipe(map(x => x?.minstep ?? null))));
+
+    this.form.valueChanges
+      .pipe(
+        distinctUntilChanged((prev, curr) => prev.price === curr.price && prev.instrumentKey === curr.instrumentKey)
```
Comment (agushasok) [inline src/app/modules/orders-basket/components/orders-basket-item/orders-basket-item.component.ts:253]: отписка

**Review by PilgrimViis — APPROVED** [review]
