### PR TITLE
#783 fix auto shrink bug

### LINKED ISSUE #783: [BUG] При расширении виджета вправо от дашборда и небольшом сужении виджет продолжает уменьшаться
### Опишите баг

После растягивания вправо от дашборда крайних "правых "виджетов и их медленном сужении, не отпуская мышь, виджеты продолжают суживаться до своих минимальных размеров ширины. 

### Воспроизведение

1. Привести дашборд к "стандартному виду".
2. Растянуть виджет "Инфо" вправо от дашборда.
3. Немного сузить его с левой стороны, не отпуская мышь.
4. Повторить для виджета "Выбор инструмента".

### Среда.

Windows 10
Google Chrome

### Ожидаемое поведение

Никакой из виджетов "не сворачивается" и сужается/расширяется до размеров, заданных пользователем.

### Скриншоты

https://user-images.githubusercontent.com/88287882/212917206-9fcfe4cb-b565-4b39-b76c-23f3f9cec7f2.mp4

### Дополнительная информация

_No response_

### Правила

- [X] Я согласен следовать правилам

### PR DESCRIPTION
**Pull request by agushasok**
Fixes #783 

# Description

fix auto shrink bug

# Testing

see in linked issue
 
# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/app/modules/dashboard/components/dashboard/dashboard.component.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class DashboardComponent implements OnInit {
           margin: 5,
           outerMargin: true,
           outerMarginTop: null,
-          outerMarginRight: null,
+          outerMarginRight: 6,
```
Comment (agushasok) [inline src/app/modules/dashboard/components/dashboard/dashboard.component.ts:84]: оставить коммент для чего это

**Review by PilgrimViis — APPROVED** [review]
