### PR TITLE
#1093 fix avg volume col, add curr volume col

### LINKED ISSUE #1093: [TECHNICAL]  Использовать поле volume из API для отображения объема в позициях
### Опишите проблему, которую решает ваша фича

Для облигаций значение "Объем" в таблицей позиций блоттера некорректное, т.к. вычисляется как ср. цена * кол-во. Для облигаций это значение должно вычисляться иначе.
image

### Опишите предлагаемое вами решение

API присылает два поля 
image
volume - средняя стоимость актива
currentVolume - стоимость по текущей цене

1. Нужно использовать значения из API
2. Логичнее отображать текущую стоимость актива, а не среднюю. Или отображать оба значения

### Опишите альтернативные решения, о которых вы думали

_No response_

### Дополнительная информация

_No response_

### Правила

- [X] Я согласен следовать правилам

### PR DESCRIPTION
**Pull request by agushasok**
Fixes #1093 

# Description

fix average volume column
add current volume column

# Testing

see in linked issue

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/app/modules/blotter/components/positions/positions.component.ts [hunk 1]
```diff
@@ -137,10 +137,18 @@ export class PositionsComponent implements OnInit, AfterViewInit, OnDestroy {
...
       sortFn: (a: PositionDisplay, b: PositionDisplay) => a.volume - b.volume,
-      tooltip: 'Объём',
+      tooltip: 'Объём по позиции, расчитанный по средней цене',
+      minWidth: 60
+    },
+    {
+      id: 'currentVolume',
+      displayName: 'Тек. объём',
+      sortOrder: null,
+      sortFn: (a: PositionDisplay, b: PositionDisplay) => a.volume - b.volume,
```
Comment (sbelashevskiy) [inline src/app/modules/blotter/components/positions/positions.component.ts:150]: некорректная сортировка

**Review by sbelashevskiy — CHANGES_REQUESTED** [review]

**Review by sbelashevskiy — APPROVED** [review]
