### PR TITLE
fix numeric field

### LINKED ISSUE #739: [FEATURE] В полях ввода вводить разделитель дробной части независимо от раскладки
### Опишите проблему, которую решает ваша фича

Неудобно, что при вводе цены нужно контролировать раскладку клавиатуры, чтобы поставить точку разделителем. Особенно неудобно, если цена вводится с numpad - части клавиатуры, особенно тем, у кого этот блок вынесен отдельным устройством. Так же при копировании цены из внешних источников, если там в качестве разделителя выбрана запятая, необходимое значение так же не подставится.

### Опишите предлагаемое вами решение

1. В полях ввода (цены) вводить необходимый разделитель (точку) независимо от раскладки (при вводе запятой на русской раскладке).
2. При подстановке в поле ввода с дробной частью (цены) значения из буфера обмена заменять разделитель на необходимый (запятую на точку).

### Опишите альтернативные решения, о которых вы думали

_No response_

### Дополнительная информация

_No response_

### Правила

- [X] Я согласен следовать правилам

### PR DESCRIPTION
**Pull request by agushasok**
Fixes #739 

# Description

fix numeric field behaviour when user insert copied value

# Testing

copy some numeric value
paste in numeric field

# Risk

No major changes

# Do you agree with those?
- [] I agree to follow the [Contributing guidelines](https://github.com/alor-broker/Astras-Trading-UI/blob/master/CONTRIBUTING.md)
- [] I agree to follow the terms of the [Code of Conduct](https://github.com/alor-broker/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: src/app/shared/directives/numerical.directive.ts [hunk 1]
```diff
@@ -38,6 +38,29 @@ export class NumericalDirective {
...
+      const selectionTotal = (<HTMLInputElement>event.target).selectionEnd! - selectionStart;
+
+      let newValue = (this._el.nativeElement.value ?? '').split('');
+      newValue.splice((<HTMLInputElement>event.target).selectionStart, selectionTotal, event.data);
+      newValue = newValue.join('');
+      newValue = newValue.replace(/,/g, '.');
+
+      if (isNaN(newValue)) {
+        event.stopPropagation();
+        event.preventDefault();
```
Comment (sbelashevskiy) [inline src/app/shared/directives/numerical.directive.ts:52]: судя по коду event.stopPropagation(); и event.preventDefault(); можно вызвать независимо от условия

**Review by sbelashevskiy — CHANGES_REQUESTED** [review]

**Review by sbelashevskiy — APPROVED** [review]
